### ISSUE TITLE
Connection Pool for PostgreSQL

### ISSUE THREAD

**Issue by tonykolomeytsev** [tonykolomeytsev/mpeix-backend-schedule-service#6]
Подключить к проекту вот эту штуку: https://github.com/brettwooldridge/HikariCP
Позволит устранить очередь при подключении к БД нескольких одновременных запросов.

**Comment by mazuninky** [comment]
Ну чё там с пулами?

**Comment by tonykolomeytsev** [comment]
Будут завтра пулы пулы, параллельно начну пилить search-service

**Comment by mazuninky** [comment]
Лупа и пулы пошли получать реализацию, но в отделе разработки все перепутали...
